In [5]:
import pandas as pd
import numpy as np

from pathlib import Path

DATA_DIR = Path("../data/raw")
REPORT_DIR = Path("../reports")

REPORT_DIR.mkdir(parents=True, exist_ok=True)

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [6]:
files = sorted(DATA_DIR.glob("*.csv"))

print(f"Found {len(files)} CSV files")

for file in files:
    print(file.name)

Found 18 CSV files
account_status_history.csv
accounts.csv
agent_sessions.csv
agents.csv
borrowers.csv
call_attempts.csv
call_dispositions.csv
calls.csv
campaigns.csv
complaints.csv
daily_targeting.csv
data_dictionary.csv
field_visits.csv
payments.csv
promises_to_pay.csv
sms_events.csv
vendor_telephony.csv
whatsapp_events.csv

In [7]:
data = {}

for file in files:
    data[file.stem] = pd.read_csv(file)

print("Loaded datasets:")
print(list(data.keys()))

Loaded datasets:
['account_status_history', 'accounts', 'agent_sessions', 'agents', 'borrowers', 'call_attempts', 'call_dispositions', 'calls', 'campaigns', 'complaints', 'daily_targeting', 'data_dictionary', 'field_visits', 'payments', 'promises_to_pay', 'sms_events', 'vendor_telephony', 'whatsapp_events']

In [8]:
inventory = []

for name, df in data.items():
    inventory.append({
        "dataset": name,
        "rows": len(df),
        "columns": len(df.columns),
        "duplicate_rows": df.duplicated().sum(),
        "memory_mb": round(
            df.memory_usage(deep=True).sum() / 1024**2,
            2
        )
    })

inventory = pd.DataFrame(inventory)

inventory = inventory.sort_values(
    "rows",
    ascending=False
).reset_index(drop=True)

display(inventory)

                   dataset    rows  columns  duplicate_rows  memory_mb
0            call_attempts  120000        9               0      56.13
1                    calls   91350       11            1271      52.35
2          whatsapp_events   60600        8             600      28.41
3   account_status_history   60000        8               0      27.73
4               sms_events   45000        8               0      20.86
5          daily_targeting   45000        7               0      15.21
6        call_dispositions   35000        8               0      16.08
7                borrowers   30600        8             600      12.98
8                 accounts   30000       11               0      13.79
9                   agents   30000        8               0      13.73
10                payments   25500        9             486      11.85
11            field_visits   25000       10               0      12.04
12         promises_to_pay   18000        9               0       8.39
13          agent_sessions   15000        7               0       6.03
14              complaints    8000        9               0       4.13
15         data_dictionary     143        3               0       0.02
16               campaigns     120        7               0       0.05
17        vendor_telephony      15        6               0       0.00

In [9]:
inventory.to_csv(
    REPORT_DIR / "dataset_inventory.csv",
    index=False
)

In [10]:
schema_rows = []

for name, df in data.items():
    for col in df.columns:
        schema_rows.append({
            "dataset": name,
            "column": col,
            "dtype": str(df[col].dtype),
            "rows": len(df),
            "null_count": int(df[col].isna().sum()),
            "null_pct": round(df[col].isna().mean() * 100, 2),
            "unique_count": int(df[col].nunique(dropna=False)),
            "unique_pct": round(
                df[col].nunique(dropna=False) / len(df) * 100,
                2
            )
        })

schema = pd.DataFrame(schema_rows)

display(schema)

,dataset,column,dtype,rows,null_count,null_pct,unique_count,unique_pct
0,account_status_history,history_id,object,60000,0,0.0,60000,100.00
1,account_status_history,account_id,object,60000,0,0.0,25999,43.33
2,account_status_history,borrower_id,object,60000,0,0.0,11916,19.86
3,account_status_history,event_at,object,60000,0,0.0,59898,99.83
4,account_status_history,status,object,60000,0,0.0,7,0.01
...,...,...,...,...,...,...,...,...
141,whatsapp_events,event_at,object,60600,0,0.0,59892,98.83
142,whatsapp_events,message_id,object,60600,0,0.0,34831,57.48
143,whatsapp_events,event_type,object,60600,0,0.0,6,0.01
144,whatsapp_events,template_code,object,60600,0,0.0,5,0.01
145,whatsapp_events,provider_id,object,60600,0,0.0,15,0.02

In [11]:
schema.to_csv(
    REPORT_DIR / "schema_profile.csv",
    index=False
)

In [12]:
candidate_keys = schema[
    (schema["unique_pct"] >= 99.9) &
    (schema["null_count"] == 0)
].copy()

candidate_keys = candidate_keys.sort_values(
    ["dataset", "unique_pct"],
    ascending=[True, False]
)

display(candidate_keys)

,dataset,column,dtype,rows,null_count,null_pct,unique_count,unique_pct
0,account_status_history,history_id,object,60000,0,0.0,60000,100.00
8,accounts,account_id,object,30000,0,0.0,30000,100.00
11,accounts,principal_amount,float64,30000,0,0.0,29996,99.99
12,accounts,outstanding_amount,float64,30000,0,0.0,29994,99.98
16,accounts,opened_at,object,30000,0,0.0,29993,99.98
19,agent_sessions,session_id,object,15000,0,0.0,15000,100.00
21,agent_sessions,login_at,object,15000,0,0.0,14996,99.97
25,agent_sessions,logout_at,object,15000,0,0.0,14996,99.97
32,agents,joined_at,object,30000,0,0.0,29995,99.98
33,agents,updated_at,object,30000,0,0.0,29987,99.96
42,call_attempts,attempt_id,object,120000,0,0.0,120000,100.00
51,call_dispositions,disposition_id,object,35000,0,0.0,35000,100.00
54,call_dispositions,event_at,object,35000,0,0.0,34966,99.90
70,campaigns,campaign_id,object,120,0,0.0,120,100.00
74,campaigns,start_at,object,120,0,0.0,120,100.00
76,campaigns,end_at,object,120,0,0.0,120,100.00
77,complaints,complaint_id,object,8000,0,0.0,8000,100.00
85,complaints,resolution_at,object,8000,0,0.0,7998,99.98
80,complaints,event_at,object,8000,0,0.0,7997,99.96
86,daily_targeting,target_id,object,45000,0,0.0,45000,100.00
96,field_visits,visit_id,object,25000,0,0.0,25000,100.00
103,field_visits,latitude,float64,25000,0,0.0,25000,100.00
104,field_visits,longitude,float64,25000,0,0.0,25000,100.00
115,promises_to_pay,ptp_id,object,18000,0,0.0,18000,100.00
121,promises_to_pay,promised_date,object,18000,0,0.0,17992,99.96
118,promises_to_pay,event_at,object,18000,0,0.0,17990,99.94
120,promises_to_pay,promised_amount,float64,18000,0,0.0,17983,99.91
124,sms_events,sms_event_id,object,45000,0,0.0,45000,100.00
132,vendor_telephony,vendor_id,object,15,0,0.0,15,100.00
134,vendor_telephony,vendor_account_id,object,15,0,0.0,15,100.00

In [13]:
duplicates = []

for name, df in data.items():
    duplicates.append({
        "dataset": name,
        "total_rows": len(df),
        "duplicate_rows": int(df.duplicated().sum()),
        "duplicate_pct": round(
            df.duplicated().mean() * 100,
            2
        )
    })

duplicates = pd.DataFrame(duplicates)

duplicates = duplicates.sort_values(
    "duplicate_rows",
    ascending=False
)

display(duplicates)

                   dataset  total_rows  duplicate_rows  duplicate_pct
7                    calls       91350            1271           1.39
4                borrowers       30600             600           1.96
17         whatsapp_events       60600             600           0.99
13                payments       25500             486           1.91
1                 accounts       30000               0           0.00
0   account_status_history       60000               0           0.00
5            call_attempts      120000               0           0.00
6        call_dispositions       35000               0           0.00
3                   agents       30000               0           0.00
2           agent_sessions       15000               0           0.00
9               complaints        8000               0           0.00
8                campaigns         120               0           0.00
11         data_dictionary         143               0           0.00
10         daily_targeting       45000               0           0.00
12            field_visits       25000               0           0.00
14         promises_to_pay       18000               0           0.00
15              sms_events       45000               0           0.00
16        vendor_telephony          15               0           0.00

In [14]:
duplicates.to_csv(
    REPORT_DIR / "duplicate_report.csv",
    index=False
)

In [15]:
missing = []

for name, df in data.items():
    for col in df.columns:
        null_count = int(df[col].isna().sum())

        missing.append({
            "dataset": name,
            "column": col,
            "null_count": null_count,
            "null_pct": round(
                null_count / len(df) * 100,
                2
            )
        })

missing = pd.DataFrame(missing)

missing = missing.sort_values(
    "null_pct",
    ascending=False
)

display(missing.head(50))

                    dataset              column  null_count  null_pct
37                borrowers               email         895      2.92
36                borrowers               phone         614      2.01
63                    calls            agent_id        1827      2.00
49            call_attempts           vendor_id        2400      2.00
9                  accounts         borrower_id         455      1.52
110                payments   payment_reference         382      1.50
105            field_visits        scheduled_at         250      1.00
2    account_status_history         borrower_id           0      0.00
1    account_status_history          account_id           0      0.00
8                  accounts          account_id           0      0.00
10                 accounts           loan_type           0      0.00
11                 accounts    principal_amount           0      0.00
4    account_status_history              status           0      0.00
3    account_status_history            event_at           0      0.00
5    account_status_history          changed_by           0      0.00
6    account_status_history              source           0      0.00
7    account_status_history         recorded_at           0      0.00
0    account_status_history          history_id           0      0.00
17                 accounts            timezone           0      0.00
16                 accounts           opened_at           0      0.00
15                 accounts              status           0      0.00
14                 accounts        risk_segment           0      0.00
13                 accounts                 dpd           0      0.00
12                 accounts  outstanding_amount           0      0.00
22           agent_sessions             channel           0      0.00
19           agent_sessions          session_id           0      0.00
26                   agents            agent_id           0      0.00
27                   agents       employee_code           0      0.00
28                   agents          agent_name           0      0.00
29                   agents           vendor_id           0      0.00
30                   agents                team           0      0.00
23           agent_sessions           device_id           0      0.00
20           agent_sessions            agent_id           0      0.00
18                 accounts      schema_version           0      0.00
33                   agents          updated_at           0      0.00
32                   agents           joined_at           0      0.00
31                   agents              status           0      0.00
35                borrowers                name           0      0.00
38                borrowers                city           0      0.00
39                borrowers          created_at           0      0.00
40                borrowers          updated_at           0      0.00
34                borrowers         borrower_id           0      0.00
41                borrowers               state           0      0.00
42            call_attempts          attempt_id           0      0.00
44            call_attempts         borrower_id           0      0.00
43            call_attempts          account_id           0      0.00
45            call_attempts            event_at           0      0.00
46            call_attempts             call_id           0      0.00
24           agent_sessions            timezone           0      0.00
21           agent_sessions            login_at           0      0.00

In [16]:
missing.to_csv(
    REPORT_DIR / "missing_values.csv",
    index=False
)

In [17]:
date_columns = []

for name, df in data.items():
    for col in df.columns:
        if any(
            x in col.lower()
            for x in ["date", "time", "timestamp", "at"]
        ):
            date_columns.append({
                "dataset": name,
                "column": col
            })

date_columns = pd.DataFrame(date_columns)

display(date_columns)

                   dataset             column
0   account_status_history           event_at
1   account_status_history             status
2   account_status_history        recorded_at
3                 accounts             status
4                 accounts          opened_at
5                 accounts           timezone
6           agent_sessions           login_at
7           agent_sessions           timezone
8           agent_sessions          logout_at
9                   agents             status
10                  agents          joined_at
11                  agents         updated_at
12               borrowers         created_at
13               borrowers         updated_at
14               borrowers              state
15           call_attempts         attempt_id
16           call_attempts           event_at
17           call_attempts         attempt_no
18           call_attempts     attempt_status
19       call_dispositions           event_at
20                   calls           event_at
21                   calls        call_status
22                   calls       duration_sec
23                   calls           timezone
24               campaigns   strategy_version
25               campaigns           start_at
26               campaigns             end_at
27              complaints           event_at
28              complaints             status
29              complaints      resolution_at
30         daily_targeting        target_date
31         daily_targeting             status
32         data_dictionary            dataset
33            field_visits           event_at
34            field_visits           latitude
35            field_visits       scheduled_at
36                payments           event_at
37                payments     payment_status
38         promises_to_pay           event_at
39         promises_to_pay      promised_date
40         promises_to_pay             status
41              sms_events           event_at
42              sms_events      template_code
43        vendor_telephony           timezone
44        vendor_telephony             status
45         whatsapp_events  whatsapp_event_id
46         whatsapp_events           event_at
47         whatsapp_events      template_code

In [18]:
date_ranges = []

for name, df in data.items():

    for col in df.columns:

        if not any(
            x in col.lower()
            for x in ["date", "time", "timestamp", "at"]
        ):
            continue

        parsed = pd.to_datetime(
            df[col],
            errors="coerce"
        )

        date_ranges.append({
            "dataset": name,
            "column": col,
            "min_date": parsed.min(),
            "max_date": parsed.max(),
            "invalid_dates": int(parsed.isna().sum())
        })

date_ranges = pd.DataFrame(date_ranges)

display(date_ranges)

C:\Users\ridhi\AppData\Local\Temp\ipykernel_10052\2705481916.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(
C:\Users\ridhi\AppData\Local\Temp\ipykernel_10052\2705481916.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(
C:\Users\ridhi\AppData\Local\Temp\ipykernel_10052\2705481916.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(
C:\Users\ridhi\AppData\Local\Temp\ipykernel_10052\2705481916.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(
C:\Users\ridhi\AppData\Local\Temp\ipykernel_10052\2705481916.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(
C:\Users\ridhi\AppData\Local\Temp\ipykernel_10052\2705481916.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(
C:\Users\ridhi\AppData\Local\Temp\ipykernel_10052\2705481916.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(
C:\Users\ridhi\AppData\Local\Temp\ipykernel_10052\2705481916.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(
C:\Users\ridhi\AppData\Local\Temp\ipykernel_10052\2705481916.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(
C:\Users\ridhi\AppData\Local\Temp\ipykernel_10052\2705481916.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(
C:\Users\ridhi\AppData\Local\Temp\ipykernel_10052\2705481916.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(
C:\Users\ridhi\AppData\Local\Temp\ipykernel_10052\2705481916.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(
C:\Users\ridhi\AppData\Local\Temp\ipykernel_10052\2705481916.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(
C:\Users\ridhi\AppData\Local\Temp\ipykernel_10052\2705481916.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(
C:\Users\ridhi\AppData\Local\Temp\ipykernel_10052\2705481916.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(
C:\Users\ridhi\AppData\Local\Temp\ipykernel_10052\2705481916.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(
C:\Users\ridhi\AppData\Local\Temp\ipykernel_10052\2705481916.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(
C:\Users\ridhi\AppData\Local\Temp\ipykernel_10052\2705481916.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(
C:\Users\ridhi\AppData\Local\Temp\ipykernel_10052\2705481916.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(
C:\Users\ridhi\AppData\Local\Temp\ipykernel_10052\2705481916.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(
C:\Users\ridhi\AppData\Local\Temp\ipykernel_10052\2705481916.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(

,dataset,column,min_date,max_date,invalid_dates
0,account_status_history,event_at,2026-01-01 00:01:08.000000000,2026-08-08 23:50:45.000000000,0
1,account_status_history,status,NaT,NaT,60000
2,account_status_history,recorded_at,2025-12-31 01:26:29.000000000,2026-08-09 22:02:27.000000000,0
3,accounts,status,NaT,NaT,30000
4,accounts,opened_at,2024-01-01 00:02:27.000000000,2025-11-30 23:52:36.000000000,0
5,accounts,timezone,NaT,NaT,30000
6,agent_sessions,login_at,2026-01-01 00:01:57.000000000,2026-08-08 23:51:54.000000000,0
7,agent_sessions,timezone,NaT,NaT,15000
8,agent_sessions,logout_at,2026-01-01 04:48:48.000000000,2026-08-09 07:50:12.000000000,0
9,agents,status,NaT,NaT,30000
10,agents,joined_at,2024-01-01 00:10:05.000000000,2025-11-30 23:23:30.000000000,0
11,agents,updated_at,2025-01-01 00:57:32.000000000,2026-08-03 23:45:38.000000000,0
12,borrowers,created_at,2025-01-01 00:14:38.000000000,2026-08-03 23:37:55.000000000,0
13,borrowers,updated_at,2025-01-01 00:19:40.000000000,2026-08-03 23:48:36.000000000,0
14,borrowers,state,NaT,NaT,30600
15,call_attempts,attempt_id,NaT,NaT,120000
16,call_attempts,event_at,2026-01-01 00:01:18.000000000,2026-08-08 23:58:40.000000000,0
17,call_attempts,attempt_no,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000007,0
18,call_attempts,attempt_status,NaT,NaT,120000
19,call_dispositions,event_at,2026-01-01 00:10:00.000000000,2026-08-08 23:50:50.000000000,0
20,calls,event_at,2025-12-29 06:52:37.000000000,2026-08-12 15:43:05.000000000,0
21,calls,call_status,NaT,NaT,91350
22,calls,duration_sec,1970-01-01 00:00:00.000000000,1970-01-01 00:00:00.000000899,0
23,calls,timezone,NaT,NaT,91350
24,campaigns,strategy_version,NaT,NaT,120
25,campaigns,start_at,2026-01-01 09:34:51.000000000,2026-05-29 20:31:27.000000000,0
26,campaigns,end_at,2026-01-16 12:12:50.000000000,2026-08-16 18:13:39.000000000,0
27,complaints,event_at,2026-01-01 00:38:02.000000000,2026-08-08 23:35:33.000000000,0
28,complaints,status,NaT,NaT,8000
29,complaints,resolution_at,2026-01-02 07:36:01.000000000,2026-08-26 13:22:27.000000000,0
30,daily_targeting,target_date,2026-01-01 00:00:00.000000000,2026-08-08 00:00:00.000000000,0
31,daily_targeting,status,NaT,NaT,45000
32,data_dictionary,dataset,NaT,NaT,143
33,field_visits,event_at,2026-01-01 00:07:53.000000000,2026-08-08 23:50:03.000000000,0
34,field_visits,latitude,1970-01-01 00:00:00.000000008,1970-01-01 00:00:00.000000034,0
35,field_visits,scheduled_at,2025-12-31 05:21:55.000000000,2026-08-08 21:50:07.000000000,250
36,payments,event_at,2026-01-01 00:14:40.000000000,2026-08-08 23:50:23.000000000,0
37,payments,payment_status,NaT,NaT,25500
38,promises_to_pay,event_at,2026-01-01 00:24:14.000000000,2026-08-08 23:59:33.000000000,0
39,promises_to_pay,promised_date,2026-01-02 04:36:18.000000000,2026-09-06 21:23:52.000000000,0
40,promises_to_pay,status,NaT,NaT,18000
41,sms_events,event_at,2026-01-01 00:04:16.000000000,2026-08-08 23:46:06.000000000,0
42,sms_events,template_code,NaT,NaT,45000
43,vendor_telephony,timezone,NaT,NaT,15
44,vendor_telephony,status,NaT,NaT,15
45,whatsapp_events,whatsapp_event_id,NaT,NaT,60600
46,whatsapp_events,event_at,2026-01-01 00:01:49.000000000,2026-08-08 23:56:16.000000000,0
47,whatsapp_events,template_code,NaT,NaT,60600

In [19]:
date_ranges.to_csv(
    REPORT_DIR / "date_ranges.csv",
    index=False
)

In [20]:
categorical_values = []

for name, df in data.items():

    for col in df.columns:

        if df[col].dtype == "object":
            unique_count = df[col].nunique(dropna=False)

            if unique_count <= 30:
                values = df[col].value_counts(
                    dropna=False
                ).to_dict()

                categorical_values.append({
                    "dataset": name,
                    "column": col,
                    "unique_count": unique_count,
                    "values": values
                })

categorical_values = pd.DataFrame(categorical_values)

display(categorical_values)

,dataset,column,unique_count,values
0,account_status_history,status,7,"{'PAID': 8650, 'CLOSED': 8614, 'DELINQUENT': 8..."
1,account_status_history,source,5,"{'CORE': 12079, 'BATCH': 12073, 'CALL': 12028,..."
2,accounts,loan_type,5,"{'CREDIT_CARD': 6080, 'AUTO': 6079, 'PERSONAL'..."
3,accounts,risk_segment,4,"{'HIGH': 7552, 'MEDIUM': 7533, 'LOW': 7513, 'N..."
4,accounts,status,4,"{'ACTIVE': 7539, 'CLOSED': 7496, 'PAID': 7486,..."
5,accounts,timezone,3,"{'UTC': 10096, 'Asia/Kolkata': 9981, 'Asia/Dub..."
6,accounts,schema_version,3,"{'v1': 10152, 'v2': 10026, 'v3': 9822}"
7,agent_sessions,channel,4,"{'WHATSAPP': 3810, 'FIELD': 3796, 'VOICE': 374..."
8,agent_sessions,timezone,2,"{'Asia/Kolkata': 7506, 'UTC': 7494}"
9,agents,agent_name,10,"{'Sneha Das': 3151, 'Amit Kumar': 3119, 'Priya..."
10,agents,vendor_id,15,"{'VND0000014': 2069, 'VND0000007': 2032, 'VND0..."
11,agents,team,5,"{'T1': 6095, 'T2': 6005, 'FIELD': 6002, 'DIGIT..."
12,agents,status,3,"{'ACTIVE': 10083, 'INACTIVE': 10066, 'SUSPENDE..."
13,borrowers,name,10,"{'Rohan Patel': 3144, 'Amit Kumar': 3119, 'Vik..."
14,borrowers,city,10,"{'Delhi': 3171, 'Hyderabad': 3119, 'Bhubaneswa..."
15,borrowers,state,9,"{'Maharashtra': 6092, 'Delhi': 3171, 'Telangan..."
16,call_attempts,vendor_id,16,"{'VND0000014': 8058, 'VND0000001': 7962, 'VND0..."
17,call_attempts,attempt_status,5,"{'RINGING': 24087, 'NO_ANSWER': 24042, 'BUSY':..."
18,call_dispositions,disposition_code,9,"{'NO_CONTACT': 4010, 'WRONG_NUMBER': 3946, 'PR..."
19,call_dispositions,disposition_version,3,"{'legacy': 11726, 'v2': 11654, 'v1': 11620}"
20,calls,direction,2,"{'OUTBOUND': 84151, 'INBOUND': 7199}"
21,calls,vendor_id,15,"{'VND0000010': 6248, 'VND0000011': 6177, 'VND0..."
22,calls,call_status,5,"{'NO_ANSWER': 18363, 'BUSY': 18330, 'FAILED': ..."
23,calls,timezone,3,"{'Asia/Kolkata': 30485, 'Asia/Dubai': 30464, '..."
24,campaigns,campaign_name,5,"{'30DPD_W1': 28, 'NPA_RECOVERY': 28, 'BOUNCE':..."
25,campaigns,channel,5,"{'WHATSAPP': 31, 'SMS': 28, 'MIXED': 23, 'VOIC..."
26,campaigns,strategy_version,4,"{'legacy': 37, 'v3': 32, 'v2': 27, 'v1': 24}"
27,campaigns,target_definition,5,"{'DPD>=60': 31, 'HIGH_RISK': 25, 'PROMISE_BROK..."
28,complaints,complaint_type,7,"{'AGENT_BEHAVIOUR': 1202, 'PRIVACY': 1155, 'DI..."
29,complaints,severity,4,"{'MEDIUM': 2047, 'HIGH': 1997, 'LOW': 1988, 'C..."
30,complaints,status,4,"{'OPEN': 2096, 'INVESTIGATING': 2005, 'CLOSED'..."
31,complaints,source,5,"{'FIELD': 1647, 'EMAIL': 1607, 'WHATSAPP': 158..."
32,daily_targeting,recommended_channel,4,"{'FIELD': 11365, 'SMS': 11221, 'WHATSAPP': 112..."
33,daily_targeting,status,4,"{'EXPIRED': 11371, 'CONTACTED': 11254, 'QUEUED..."
34,data_dictionary,dataset,17,"{'accounts': 11, 'calls': 11, 'field_visits': ..."
35,data_dictionary,dtype,4,"{'object': 109, 'datetime64[ns]': 24, 'float64..."
36,field_visits,visit_type,4,"{'FIRST_VISIT': 6275, 'FOLLOWUP': 6271, 'NOTIC..."
37,field_visits,outcome,6,"{'WRONG_ADDRESS': 4221, 'CONTACTED': 4205, 'PT..."
38,payments,payment_status,4,"{'SUCCESS': 17880, 'FAILED': 3744, 'PENDING': ..."
39,payments,payment_method,5,"{'CARD': 5227, 'NACH': 5158, 'NETBANKING': 505..."
40,payments,provider_id,15,"{'VND0000007': 1773, 'VND0000012': 1748, 'VND0..."
41,promises_to_pay,status,4,"{'BROKEN': 4553, 'CANCELLED': 4543, 'KEPT': 44..."
42,promises_to_pay,source,4,"{'CALL': 4571, 'FIELD': 4546, 'SMS': 4449, 'WH..."
43,sms_events,event_type,4,"{'SENT': 11391, 'FAILED': 11251, 'DELIVERED': ..."
44,sms_events,template_code,4,"{'PAYMENT_LINK': 11420, 'DUE_REMINDER': 11256,..."
45,sms_events,provider_id,15,"{'VND0000012': 3087, 'VND0000010': 3068, 'VND0..."
46,vendor_telephony,vendor_id,15,"{'VND0000001': 1, 'VND0000002': 1, 'VND0000003..."
47,vendor_telephony,vendor_name,5,"{'Airtel': 5, 'Twilio': 3, 'Knowlarity': 3, 'E..."
48,vendor_telephony,vendor_account_id,15,"{'VAC342762': 1, 'VAC456766': 1, 'VAC074211': ..."
49,vendor_telephony,timezone,2,"{'UTC': 8, 'Asia/Kolkata': 7}"
50,vendor_telephony,status,2,"{'INACTIVE': 9, 'ACTIVE': 6}"
51,vendor_telephony,schema_version,3,"{'v1': 7, 'v3': 6, 'v2': 2}"
52,whatsapp_events,event_type,6,"{'SENT': 10244, 'PAYMENT_CLICK': 10180, 'FAILE..."
53,whatsapp_events,template_code,5,"{'PTP_01': 12275, 'FIELD_VISIT': 12177, 'PAYME..."
54,whatsapp_events,provider_id,15,"{'VND0000002': 4177, 'VND0000007': 4154, 'VND0..."

In [21]:
id_columns = []

for name, df in data.items():

    for col in df.columns:

        if "id" in col.lower():
            id_columns.append({
                "dataset": name,
                "column": col,
                "unique_values": df[col].nunique(dropna=False),
                "nulls": df[col].isna().sum()
            })

id_columns = pd.DataFrame(id_columns)

display(id_columns)

                   dataset             column  unique_values  nulls
0   account_status_history         history_id          60000      0
1   account_status_history         account_id          25999      0
2   account_status_history        borrower_id          11916      0
3                 accounts         account_id          30000      0
4                 accounts        borrower_id          10944    455
5           agent_sessions         session_id          15000      0
6           agent_sessions           agent_id           1000      0
7           agent_sessions          device_id           1500      0
8                   agents           agent_id           1000      0
9                   agents          vendor_id             15      0
10               borrowers        borrower_id          11015      0
11           call_attempts         attempt_id         120000      0
12           call_attempts         account_id          29451      0
13           call_attempts        borrower_id          12000      0
14           call_attempts            call_id          66244      0
15           call_attempts           agent_id           1000      0
16           call_attempts          vendor_id             16   2400
17       call_dispositions     disposition_id          35000      0
18       call_dispositions         account_id          20603      0
19       call_dispositions        borrower_id          11359      0
20       call_dispositions            call_id          28971      0
21       call_dispositions           agent_id           1000      0
22                   calls            call_id          90000      0
23                   calls         account_id          28408      0
24                   calls        borrower_id          11992      0
25                   calls           agent_id           1001   1827
26                   calls        campaign_id            120      0
27                   calls          vendor_id             15      0
28               campaigns        campaign_id            120      0
29              complaints       complaint_id           8000      0
30              complaints         account_id           7034      0
31              complaints        borrower_id           5839      0
32         daily_targeting          target_id          45000      0
33         daily_targeting         account_id          23344      0
34         daily_targeting        campaign_id            120      0
35            field_visits           visit_id          25000      0
36            field_visits         account_id          16908      0
37            field_visits        borrower_id          10537      0
38            field_visits           agent_id           1000      0
39                payments         payment_id          25000      0
40                payments         account_id          16934      0
41                payments        borrower_id          10474      0
42                payments        provider_id             15      0
43         promises_to_pay             ptp_id          18000      0
44         promises_to_pay         account_id          13532      0
45         promises_to_pay        borrower_id           9299      0
46         promises_to_pay           agent_id           1000      0
47              sms_events       sms_event_id          45000      0
48              sms_events         account_id          23207      0
49              sms_events        borrower_id          11728      0
50              sms_events         message_id          27001      0
51              sms_events        provider_id             15      0
52        vendor_telephony          vendor_id             15      0
53        vendor_telephony  vendor_account_id             15      0
54         whatsapp_events  whatsapp_event_id          60000      0
55         whatsapp_events         account_id          25924      0
56         whatsapp_events        borrower_id          11917      0
57         whatsapp_events         message_id          34831      0
58         whatsapp_events        provider_id             15      0

In [22]:
accounts = data["accounts"]
borrowers = data["borrowers"]

missing_borrowers = accounts[
    ~accounts["borrower_id"].isin(
        borrowers["borrower_id"]
    )
]

print("Accounts with invalid/missing borrower:")
print(len(missing_borrowers))

Accounts with invalid/missing borrower:
2913

In [23]:
calls = data["calls"]

invalid_call_accounts = calls[
    ~calls["account_id"].isin(
        accounts["account_id"]
    )
]

print(
    "Calls with invalid account:",
    len(invalid_call_accounts)
)

Calls with invalid account: 0

In [24]:
payments = data["payments"]

invalid_payment_accounts = payments[
    ~payments["account_id"].isin(
        accounts["account_id"]
    )
]

print(
    "Payments with invalid account:",
    len(invalid_payment_accounts)
)

Payments with invalid account: 0

In [25]:
agents = data["agents"]

invalid_call_agents = calls[
    calls["agent_id"].notna() &
    ~calls["agent_id"].isin(agents["agent_id"])
]

print(
    "Calls with invalid agent:",
    len(invalid_call_agents)
)

Calls with invalid agent: 0

In [26]:
phase1_summary = {
    "datasets": len(data),
    "total_rows": sum(len(df) for df in data.values()),
    "tables_with_duplicates": int(
        (duplicates["duplicate_rows"] > 0).sum()
    ),
    "tables_with_missing_values": int(
        (missing["null_count"] > 0).groupby(
            missing["dataset"]
        ).any().sum()
    )
}

phase1_summary

{'datasets': 18,
 'total_rows': 639328,
 'tables_with_duplicates': 4,
 'tables_with_missing_values': 6}